motoadmin/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views

counter_party_url = [
    path('', login_required(views.CounterPartyView.as_view()), name='list'),
    path('add/', login_required(views.CounterPartyCreateView.as_view()), name='add'),
    path('each/<int:pk>', login_required(views.CounterPartyEachView.as_view()), name='each'),
    path('update/<int:pk>', login_required(views.CounterPartyUpdateView.as_view()), name='update'),
]


order_urls = [
    path('', login_required(views.OrderView.as_view()), name='list'),
    path('add/', login_required(views.OrderCreateView.as_view()), name='add'),
    path('update/<int:pk>', login_required(views.OrderUpdateView.as_view()), name='update'),
    path('each/<int:pk>', login_required(views.OrderDetailView.as_view()), name='each'),
    path('action/<int:pk>', login_required(views.order_action), name='action'),
    path('add_order_item/<int:pk>', login_required(views.OrderItemCreateView.as_view()), name='order_item_add'),
]


income_urls = [
    path('', login_required(views.IncomeView.as_view()), name='list'),
]


product_urls = [
    path('', login_required(views.ProductListVIew.as_view()), name='list'),
    path('add/', login_required(views.AddProductCreateView.as_view()), name='add'),
    path('edit/<int:pk>', login_required(views.ProductUpdateView.as_view()), name='edit'),
]


urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', login_required(views.logout_view), name='logout'),
    path('product/', include((product_urls, 'motoadmin'), namespace='product')),
    path('order/', include((order_urls, 'motoadmin'), namespace='order')),
    path('counter-party/', include((counter_party_url, 'motoadmin'), namespace='counter-party')),
    path('income/', include((income_urls, 'motoadmin'), namespace='income')),
    path('outcome/', login_required(views.OutComeView.as_view()), name='outcome'),
    path('pdf/', login_required(views.GeneratePdf.as_view()), name='pdf'),
]

handler404 = views.error_404

system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('motoadmin.urls')),
    path('', include(('motoadmin1.urls', 'motoadmin1'))),
]

motoadmin/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


PRODUCT_STATUS = (
    ('Активный', 'Активный'),
    ('Неактивный', 'Неактивный'),
)


class Product(models.Model):
    title = models.CharField(max_length=500)
    size = models.CharField(max_length=500)
    price = models.FloatField()
    status = models.CharField(max_length=500, choices=PRODUCT_STATUS)
    code = models.CharField(max_length=500, default=0, blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.date.today)
    count = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return f"{self.title} / {self.count}"


COUNTER_STATUS = (
    (1, "Активный"),
    (2, "Неактивный"),
    (3, "Удаленный"),
)


class CounterParty(models.Model):
    name = models.CharField(max_length=500)
    balance_uzs = models.FloatField(blank=True, null=True, default=0)
    balance_usd = models.FloatField(blank=True, null=True, default=0)
    org_name = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    phone2 = models.CharField(max_length=500, blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    inn = models.CharField(max_length=500, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)
    status = models.IntegerField(choices=COUNTER_STATUS)
    sms = models.CharField(max_length=500, blank=True, null=True)
    extra_info = models.CharField(max_length=1000, blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.date.today)

    def __str__(self):
        return f"{self.name} / {self.org_name}"


ORDER_STATUS = (
    (1, "Удалён"),
    (2, "Закрытый"),
    (3, "Оплаченный/Долговой "),
    (4, "Завершенный"),
    (5, "В процессе"),
)


class Order(models.Model):
    created_at = models.DateTimeField(default=datetime.date.today)
    counter_party = models.ForeignKey(CounterParty, on_delete=models.CASCADE)
    status = models.IntegerField(choices=ORDER_STATUS, default=5)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    total_uzs = models.FloatField(default=0, blank=True, null=True)
    total_usd = models.FloatField(default=0, blank=True, null=True)
    rate = models.FloatField(default=0, blank=True, null=True)


PAYMENT_TYPE = (
    ('Наличные', 'Наличные'),
    ('Перечисление', 'Перечисление'),
    ('Карта', 'Карта'),
)
CURRENCY = (
    ('Доллар', 'Доллар'),
    ('Сум', 'Сум'),
)


class OrderItem(models.Model):
    sum = models.PositiveIntegerField(verbose_name='Сумма')
    currency = models.CharField(max_length=200, choices=CURRENCY, verbose_name='Валюта')
    payment_type = models.CharField(max_length=500, choices=PAYMENT_TYPE, verbose_name='Метод оплаты')
    for_delivery = models.BooleanField(default=False, verbose_name='За доставку?')
    created_at = models.DateTimeField(default=datetime.date.today)
    description = models.CharField(max_length=500, blank=True, null=True, verbose_name='Комментарии')
    rate = models.FloatField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)


class OrderReturnItem(models.Model):
    created_at = models.DateTimeField(auto_created=True)
    count = models.FloatField()
    status = models.IntegerField()
    order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_uzs = models.FloatField()
    total_usd = models.FloatField()
    rate = models.FloatField()

motoadmin/forms.py
from django.forms import ModelForm
from .models import CounterParty, Order, OrderItem, Product


class CounterPartyForm(ModelForm):
    class Meta:
        model = CounterParty
        exclude = ('balance_usd', 'balance_uzs', 'created_at')


class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ('created_at', 'status', 'user', 'total_uzs', 'total_usd', 'rate')


class OrderEditForm(ModelForm):
    class Meta:
        model = Order
        exclude = ('created_at', )


class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        exclude = ('created_at', 'rate')


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'count')

motoadmin/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate
from django.views import View
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth import login, logout
from django.http import HttpResponse
from .models import Product, CounterParty, Order, OrderItem
from .forms import CounterPartyForm, OrderItemForm
from .utils import render_to_pdf


class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        pdf = render_to_pdf('pdf/invoice.html')
        return HttpResponse(pdf, content_type='application/pdf')


def logout_view(request):
    logout(request)
    return redirect('/')


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('product:list')
        return render(request, 'login.html')

    def post(self, request):
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user:
            login(request, user)
            return redirect('product:list')
        return render(request, 'login.html')


class ProductListVIew(ListView):
    model = Product
    template_name = 'product.html'


class AddProductCreateView(CreateView):
    model = Product
    fields = ('title', 'size', 'price', 'status', 'code')
    template_name = 'product_add.html'
    success_url = reverse_lazy('product:list')


class ProductUpdateView(UpdateView):
    model = Product
    fields = ('title', 'size', 'price', 'status', 'code')
    template_name = 'product_edit.html'
    success_url = reverse_lazy('product:list')


class OrderView(ListView):
    model = Order
    template_name = 'order.html'


class OrderCreateView(CreateView):
    model = Order
    fields = ('counter_party', )
    template_name = 'order_add.html'
    success_url = reverse_lazy('order:list')


class OrderUpdateView(UpdateView):
    model = Order
    fields = ('counter_party', 'status', 'user', 'total_uzs', 'total_usd', 'rate')
    template_name = 'order_edit.html'
    success_url = reverse_lazy('order:list')


class OrderDetailView(DetailView):
    model = Order
    template_name = 'order_each.html'

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['product'] = Product.objects.all()
        context['order_item'] = OrderItem.objects.all()
        context['form'] = OrderItemForm()
        return context


class OrderItemCreateView(CreateView):
    model = OrderItem
    form_class = OrderItemForm
    success_url = reverse_lazy('order:list')

    # def get_success_url(self, *args, **kwargs):
    #     return HttpResponse(self.request.path_info)
    # HELP
    def form_valid(self, form, **kwargs):
        order = Order.objects.get(id=self.kwargs['pk'])
        counter_party = CounterParty.objects.get(id=order.counter_party_id)
        d = form.save(commit=False)
        if form.cleaned_data['description']:
            d.description = str(form.cleaned_data['description']) + 'Оплата за доставку'
        else:
            d.description = 'Оплата за доставку'
        if not form.cleaned_data['for_delivery']:
            if form.cleaned_data['currency'] == 'Доллар':
                counter_party.balance_usd += int(form.cleaned_data['sum'])
            else:
                counter_party.balance_uzs += int(form.cleaned_data['sum'])
            counter_party.save()
            if form.cleaned_data['description']:
                d.description = str(form.cleaned_data['description']) + 'Оплата за заказ'
            else:
                d.description = 'Оплата за заказ'
        d.save()
        return super().form_valid(form)


def order_action(request, pk):
    status = int(request.POST.get('status'))
    Order.objects.filter(id=pk).update(status=status)
    return redirect(request.META['HTTP_REFERER'])


class CounterPartyView(ListView):
    model = CounterParty
    template_name = 'counter_party.html'


class CounterPartyCreateView(CreateView):
    model = CounterParty
    form_class = CounterPartyForm
    template_name = 'counter_party_add.html'
    success_url = reverse_lazy('counter-party:list')


class CounterPartyEachView(DetailView):
    model = CounterParty
    template_name = 'counter_party_each.html'


class CounterPartyUpdateView(UpdateView):
    model = CounterParty
    form_class = CounterPartyForm
    template_name = 'counter_party_edit.html'
    success_url = reverse_lazy('counter-party:list')


class IncomeView(ListView):
    model = OrderItem
    template_name = 'income.html'


class OutComeView(View):
    def get(self, request):
        context = {

        }
        return render(request, 'outcome.html', context)


def error_404(request, exception):
    return render(request, '404.html')

motoadmin/templates/counter_party.html
{% extends 'layout.html' %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Агенты</h4>
                <a class="btn btn-primary ml-auto" href="{% url 'counter-party:add' %}">Добавить</a>
            </div>
        </div>

         <div class="card shadow m-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Ф.И.О</th>
                                <th>ОРГАНИЗАЦИИ</th>
                                <th>НОМЕР ТЕЛЕФОНА</th>
                                <th>БАЛАНС (ДОЛЛАР)</th>
                                <th>БАЛАНС (СУММ)</th>
                                <th>СОЗДАНО</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for i in object_list %}
                            <tr>
                                <td>{{ i.name }}</td>
                                <td>{{ i.org_name }}</td>
                                <td>{{ i.phone }}</td>
                                <td>{{ i.balance_usd }}</td>
                                <td>{{ i.balance_uzs }}</td>
                                <td>{{ i.created_at }}</td>
                                <td class="text-center text-primary">
                                    <a href="{% url 'counter-party:update' i.id %}"><i class="fa fa-pen fa-solid"></i></a>
                                    <a href="{% url 'counter-party:each' i.id %}"><i class="fa-solid fa fa-eye"></i></a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="7" class="text-center font-weight-bold">
                                    Empty
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/counter_party_add.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Добавить Агент</h4>
            </div>
        </div>

        <div class="mx-auto card shadow m-4 p-3 w-75">
            <form method="POST" action="{% url 'counter-party:add' %}">
                {% csrf_token %}
                {{ form|crispy }}
              <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/counter_party_each.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Агент {{ counter.name }}</h4>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-9 card shadow p-3">
                    <table class="table table-striped">
                      <tbody>
                        <tr>
                          <th>Статус</th>
                          <td>{{ object.status }}</td>
                        </tr>
                        <tr>
                          <th>Название организации</th>
                          <td>{{ object.org_name }}</td>
                        </tr>
                        <tr>
                          <th>Номер телефона</th>
                          <td>{{ object.phone }}</td>
                        </tr>
                      <tr>
                          <th>Создано</th>
                          <td>{{ object.created_at }}</td>
                        </tr>
                      <tr>
                          <th>Информация</th>
                          <td>{{ object.extra_info }}</td>
                        </tr>
                      </tbody>
                    </table>
                </div>
                <div class="col-lg-3 card shadow p-3">
                    <h3>Баланс</h3>
                     <table class="table table-striped">
                      <tbody>
                        <tr>
                          <th>Сум</th>
                          <td>{{ object.balance_uzs }}</td>
                        </tr>
                        <tr>
                          <th>Доллар</th>
                          <td>{{ object.balance_usd }}</td>
                        </tr>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/counter_party_edit.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Изменить Агент</h4>
            </div>
        </div>

        <div class="mx-auto card shadow m-4 p-3 w-75">
            <form method="POST" action="#">
                {% csrf_token %}
                {{ form|crispy }}
              <button type="submit" class="btn btn-primary">Изменить</button>
            </form>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/order.html
{% extends 'layout.html' %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Заказы</h4>
                <a class="btn btn-primary ml-auto" href="{% url 'order:add' %}">Добавить</a>
            </div>
        </div>

         <div class="card shadow m-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>КОНТР АГЕНТ</th>
                                <th>СУММА(СУМ)</th>
                                <th>СУММА(ДОЛЛАР)</th>
                                <th>КУРС ВАЛЮТЫ</th>
                                <th>ДЕЙСТВИЕ</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for i in object_list %}
                            <tr>
                                <td>{{ i.id }}</td>
                                <td>{{ i.counter_party }}</td>
                                <td>{{ i.total_uzs }}</td>
                                <td>{{ i.total_usd }}</td>
                                <td>{{ i.rate }}</td>
                                <td class="text-center text-primary">
                                    <a href="{% url 'order:update' i.id %}"><i class="fa fa-pen fa-solid"></i></a>
                                    <a href="{% url 'order:each' i.id %}"><i class="fa-solid fa fa-eye"></i></a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td class="text-center font-weight-bold" colspan="6">
                                    Empty
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/order_add.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Добавить заказ</h4>
            </div>
        </div>

        <div class="mx-auto card shadow m-4 p-3 w-75">
            <form method="POST" action="{% url 'order:add' %}">
                {% csrf_token %}
                {{ form|crispy}}
              <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/order_each.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block css %}
    <style>
    .dropdown_dot {
        position: absolute;
        right: 0;
        background-color: white;
        color: black;
        width: 50%;
    }
    .dropdown_dot a:hover {
        text-decoration: none;
    }
    </style>
{% endblock %}

{% block body %}
         <div class="card shadow m-4">
            <div class="card-body">
                <div class="row border-bottom mb-3">
                    <div class="col-lg-9">
                        <div class="d-flex">
                            <h3 class="font-weight-bold">Заказ № {{ order.id }}</h3>
                            <h3 class="text-dark border-right pr-2">от {{ order.created_at }}</h3>
                            {% if order.get_status_display == 'Удалён' %}
                                <p class="bg-danger px-2 ml-2 text-white">{{ order.get_status_display }}</p>
                                {% elif order.get_status_display == 'Оплаченный/Долговой' %}
                                    <p class="bg-warning px-2 ml-2 text-white">{{ order.get_status_display }}</p>
                                {% else %}
                                    <p class="bg-primary px-2 ml-2 text-white">{{ order.get_status_display }}</p>
                            {% endif %}
                        </div>
                        <div class="d-flex my-2">
                            <h4>Агент: </h4>
                            <a href="{% url 'counter-party:each' order.counter_party_id %}" class="btn btn-primary ml-2">{{ order.counter_party }}</a>
                        </div>
                    </div>
                    <div class="col-lg-3 text-right">
                        <div>
                            <button class="btn btn-primary dot_dot"><h6>. . .</h6></button>
                            <div class="card p-2 shadow text-center dropdown_dot font-weight-bold d-none">
                                {% if order.get_status_display == 'В процессе' %}
                                    <a href="{% url 'pdf' %}" class="d-block">Распечатать фактуру</a>
                                    <a href="#" class="d-block move_order">Переместить в корзину</a>
                                    <a href="#" class="d-block bg-success close_order">Закрыт</a>
                                {% elif order.get_status_display == 'Закрытый' %}
                                    <a href="{% url 'pdf' %}" class="d-block">Распечатать фактуру</a>
                                    <a href="#" class="d-block move_order">Переместить в корзину</a>
                                    {% else %}
                                        <a href="{% url 'pdf' %}" class="d-block">Распечатать фактуру</a>
                                {% endif %}
                                <form name="close_form" method="POST" action="{% url 'order:action' order.id %}" type="hidden">
                                    {% csrf_token %}
                                    <input name="status" value="2" type="hidden">
                                </form>
                                <form name="move_form" method="POST" action="{% url 'order:action' order.id %}" type="hidden">
                                    {% csrf_token %}
                                    <input name="status" value="1" type="hidden">
                                </form>
                            </div>
                        </div>
                        <div class="my-2">
                            <p><b>Итог (UZS):</b> {{ order.total_uzs }} сум</p>
                            <p><b>Итог (USD):</b> {{ order.total_usd }} $</p>
                        </div>
                    </div>
                </div>
                <h3 class="text-dark font-weight-bold">Список товаров</h3>
                <table class="table table-striped my-5">
                  <thead>
                    <tr>
                      <th scope="col">ПРОДУКТ</th>
                      <th scope="col">РАЗМЕР</th>
                      <th scope="col">КОЛИЧЕСТВО</th>
                      <th scope="col">ЦЕНА</th>
                        <th>СУММА (UZS)</th>
                        <th>СУММА (USD)</th>
                        <th>ДЕЙСТВИЕ</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                  </tbody>
                </table>
            {% if order.get_status_display == 'В процессе' %}
                <h3 class="text-dark font-weight-bold">Продукт</h3>
                <div class="text-right">
                    <div>
                        <h3 class="text-dark font-weight-bold">Продукты В Складе</h3>
                        {% for i in product %}
                        <p>{{ i.title }}</p>
                            {% empty %}
                            <p>No products</p>
                        {% endfor %}
                    </div>
                </div>
                <div>
                    <h4 class="text-dark font-weight-bold">Добавить Продукт В Заказа</h4>
                    <a href="#" class="btn btn-primary">Добавить</a>
                </div>
                {% elif order.get_status_display == 'Закрытый' or order.get_status_display == 'Завершенный' %}
                    <h3 class="text-dark font-weight-bold my-4">Добавить Оплату Для Заказа</h3>
                    <form method="POST" action="{% url 'order:order_item_add' order.id %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                    <button class="btn btn-primary btn-md btn-block my-3" type="submit">Добавить</button>
                    </form>
                <h3 class="text-dark font-weight-bold my-4">Список Оплат По Заказу</h3>
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col">ДАТА</th>
                      <th scope="col">СУММА</th>
                      <th scope="col">ВАЛЮТА</th>
                      <th scope="col">МЕТОД ОПЛАТЫ</th>
                        <th scope="col">КОММЕНТАРИИ</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for i in order_item %}
                  <tr>
                      <th scope="row">{{ i.created_at }}</th>
                      <td>{{ i.sum }}</td>
                      <td>{{ i.currency }}</td>
                      <td>{{ i.payment_type }}</td>
                      <td>{{ i.description }}</td>
                    </tr>
                      {% empty %}
                          <tr>
                              <th scope="row" class="text-center" colspan="5">Empty</th>
                            </tr>
                  {% endfor %}
                  <tr>
                      <th scope="row"></th>
                      <td>Итог (UZS):</td>
                      <td class="uzs">0</td>
                      <td>Итог (USD):</td>
                      <td class="usd">0</td>
                  </tr>
                  </tbody>
                </table>
            {% endif %}
            </div>
        </div>

{% endblock %}

{% block js %}
    <script>
        $('.dot_dot').on('click', function(){
            $('.dropdown_dot').toggleClass('d-block');
        });

        $('.move_order').on('click', function(){
           $('form[name="move_form"]').submit();
        });
        $('.close_order').on('click', function(){
           $('form[name="close_form"]').submit();
        });

        let total_usd = 0;
        let total_uzs = 0;

        {% for i in order_item %}
            {% if i.currency == 'Доллар' %}
                total_usd += {{ i.sum }}
                    {% else %}
                        total_uzs += {{ i.sum }}
            {% endif %}
        {% endfor %}

        $('.uzs').html(total_uzs);
        $('.usd').html(total_usd);
    </script>
{% endblock %}

motoadmin/templates/order_edit.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Изменить заказ</h4>
            </div>
        </div>

        <div class="mx-auto card shadow m-4 p-3 w-75">
            <form method="POST" action="#">
                {% csrf_token %}
                {{ form|crispy}}
              <button type="submit" class="btn btn-primary">Изменить</button>
            </form>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/product.html
{% extends 'layout.html' %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Продукты</h4>
                <a href="{% url 'product:add' %}" class="btn btn-primary ml-auto">Добавить</a>
            </div>
        </div>

        <div class="card shadow m-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>НАЗВАНИЕ</th>
                                <th>КОД ПРОДУКТА</th>
                                <th>ЦЕНА</th>
                                <th>ДАТА</th>
                                <th>СТАТУС</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for i in object_list %}
                            <tr>
                                <td>{{ i.title }}</td>
                                <td>{{ i.code }}</td>
                                <td>{{ i.price }}</td>
                                <td>{{ i.created_at }}</td>
                                <td>{{ i.status }}</td>
                                <td class="text-center text-primary"><a href="{% url 'product:edit' i.id %}"><i class="fa fa-pen fa-solid"></i></a></td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td class="text-center" colspan="6">Empty</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

{% block js %}{% endblock %}

motoadmin/templates/product_add.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block css %}{% endblock %}

{% block body %}
        <div class="card m-4 border-left-primary">
            <div class="card-body d-flex">
                <h4>Добавить продукт</h4>
            </div>
        </div>

        <div class="mx-auto card shadow m-4 p-3 w-75">
            <form method="POST" action="{% url 'product:add' %}">
                {% csrf_token %}
                {{ form|crispy }}
              <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
        </div>

{% endblock %}

{% block js %}{% endblock %}